require('./urls');
require('./channel');
require('./calcul');
require('./pages/index');
require('./pages/detect');
require('./pages/perso');
require('./pages/invent');
require('./pages/transfert');
require('./pages/even');
